### ISSUE TITLE
wrong imports in templates in v2.0.0

### ISSUE THREAD

**Issue by keilhofh** [wimdeblauwe/jpearl#5]
Hi,
in 
entity-template.java
and 
entity-repository-test-template.java

you still use javax instead of jakarta...

import javax.persistence.Entity;
and 
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

respectively.

This did not work at least for me together with Spring Boot 3.
I had to use jakarta.persistence...

Greetings and thank you for making available your library.
Hans-Peter

**Comment by wimdeblauwe** [comment]
Thank you for letting me know. A fix is released now as version 2.0.1.
